name: Flutter Web Deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Flutter SDK 설치
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: latest
          cache: true
          cache-sdk: true

      # 2. Dependencies 설치
      - name: Install dependencies
        run: flutter pub get

      # 3. Apply Dart fixes
      - name: Apply Dart fixes
        run: dart fix --apply

      # 4. 정적 분석
      - name: Analyze source
        run: dart analyze

      # 5. WASM 웹 빌드
      - name: Build Flutter Web (Wasm)
        run: flutter build web --wasm

      # 6. Firebase Hosting 배포
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v14.9.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
